import type { AppData } from './types';

export const emptyData: AppData = {
  shutdowns: [],
  phases: [],
  poBsps: [],
  team: [],
  tools: [],
  progress: [],
  users: [],
  auditLogs: [],
};

export const sampleData: AppData = {
  shutdowns: [
    {
      id: 'sd-saquarema-2026',
      code: 'SD-SAQ-2026',
      client: 'SBM',
      fpso: 'FPSO Cidade de Saquarema',
      pm: 'Douglas Francisco',
      responsible: 'Planejamento STEP',
      activity: 'Shutdown Julho 2026',
      type: 'Shutdown',
      startDate: '2026-07-05',
      endDate: '2026-07-25',
      days: 21,
      status: 'Em preparação',
      priority: 'Alta',
      notes: 'Base criada a partir das planilhas de POB, ferramental, calendário e avanços.',
      createdAt: '2026-05-18T00:00:00.000Z',
      updatedAt: '2026-05-18T00:00:00.000Z',
    },
    {
      id: 'sd-anchieta-2026',
      code: 'SD-ANC-2026',
      client: 'SBM',
      fpso: 'FPSO Cidade de Anchieta',
      pm: 'Douglas Francisco',
      responsible: 'Operações Offshore',
      activity: 'Shutdown 2026',
      type: 'Shutdown',
      startDate: '2026-08-03',
      endDate: '2026-08-20',
      days: 18,
      status: 'Planejado',
      priority: 'Normal',
      notes: 'Aguardando consolidação final de equipe e PO/BSP.',
      createdAt: '2026-05-18T00:00:00.000Z',
      updatedAt: '2026-05-18T00:00:00.000Z',
    },
    {
      id: 'sd-sepetiba-2026',
      code: 'SD-SEP-2026',
      client: 'SBM',
      fpso: 'FPSO Sepetiba',
      pm: 'Douglas Francisco',
      responsible: 'IPM / Planejamento',
      activity: 'Campanha + Shutdown',
      type: 'Campanha',
      startDate: '2026-06-15',
      endDate: '2026-07-12',
      days: 28,
      status: 'Em mobilização',
      priority: 'Crítica',
      notes: 'Projeto com histograma detalhado e day rate por função.',
      createdAt: '2026-05-18T00:00:00.000Z',
      updatedAt: '2026-05-18T00:00:00.000Z',
    },
  ],
  phases: [
    { id: 'ph-1', shutdownId: 'sd-saquarema-2026', name: 'Survey', responsible: 'Equipe Técnica', startDate: '2026-06-01', endDate: '2026-06-05', status: 'Concluído', progress: 100, notes: '' },
    { id: 'ph-2', shutdownId: 'sd-saquarema-2026', name: 'ARM', responsible: 'Materiais', startDate: '2026-06-08', endDate: '2026-06-20', status: 'Em andamento', progress: 70, notes: 'Conferir ferramentas críticas.' },
    { id: 'ph-3', shutdownId: 'sd-saquarema-2026', name: 'Pré-Shutdown', responsible: 'Planejamento', startDate: '2026-06-25', endDate: '2026-07-04', status: 'Não iniciado', progress: 0, notes: '' },
    { id: 'ph-4', shutdownId: 'sd-saquarema-2026', name: 'Shutdown', responsible: 'Operação Offshore', startDate: '2026-07-05', endDate: '2026-07-25', status: 'Não iniciado', progress: 0, notes: '' },
    { id: 'ph-5', shutdownId: 'sd-sepetiba-2026', name: 'Campanha Shutdown', responsible: 'IPM', startDate: '2026-06-15', endDate: '2026-07-02', status: 'Em andamento', progress: 40, notes: '' },
    { id: 'ph-6', shutdownId: 'sd-sepetiba-2026', name: 'Pós-Shutdown', responsible: 'Documentação', startDate: '2026-07-13', endDate: '2026-07-20', status: 'Não iniciado', progress: 0, notes: '' },
  ],
  poBsps: [
    { id: 'po-1', shutdownId: 'sd-saquarema-2026', po: 'PO-4500123456', bsp: 'BSP 26-001', bpp: '', type: 'Shutdown', status: 'Aprovado', responsible: 'Comercial STEP', issueDate: '2026-05-10', receivedDate: '2026-05-12', notes: 'Contrato principal recebido.' },
    { id: 'po-2', shutdownId: 'sd-anchieta-2026', po: '', bsp: 'BSP 26-014', bpp: '', type: 'Shutdown', status: 'Pendente', responsible: 'Cliente', issueDate: '', receivedDate: '', notes: 'Aguardando PO.' },
    { id: 'po-3', shutdownId: 'sd-sepetiba-2026', po: 'PO-4500987654', bsp: '', bpp: '', type: 'Shutdown', status: 'Solicitado', responsible: 'PM', issueDate: '2026-05-16', receivedDate: '', notes: 'BSP em aprovação.' },
  ],
  team: [
    { id: 'tm-1', shutdownId: 'sd-saquarema-2026', name: 'Profissional Mecânico 01', cpf: '', company: 'STEP Oil', role: 'Mechanic', scope: 'Shutdown Period', flight: '', shift: 'Dia', arrivalDate: '2026-07-03', departureDate: '2026-07-26', status: 'Planejado', dayRate: 480, notes: '' },
    { id: 'tm-2', shutdownId: 'sd-saquarema-2026', name: 'Supervisor Offshore 01', cpf: '', company: 'STEP Oil', role: 'Supervisor', scope: 'Shutdown Period', flight: '', shift: 'Dia', arrivalDate: '2026-07-02', departureDate: '2026-07-27', status: 'Nomeado', dayRate: 750, notes: '' },
    { id: 'tm-3', shutdownId: 'sd-sepetiba-2026', name: 'IRATA N2 01', cpf: '', company: 'STEP Oil', role: 'IRATA N2', scope: 'R&L Campaign', flight: '', shift: 'Noite', arrivalDate: '2026-06-15', departureDate: '2026-07-12', status: 'Aguardando documentação', dayRate: 610, notes: 'Documentos pendentes.' },
  ],
  tools: [
    { id: 'tl-1', shutdownId: 'sd-saquarema-2026', item: 'Chave combinada jogo completo', category: 'Ferramentas Manuais', quantity: 2, unit: 'JG', status: 'Em separação', needDate: '2026-06-25', separationDate: '', sendDate: '', responsible: 'Suprimentos', notes: '' },
    { id: 'tl-2', shutdownId: 'sd-saquarema-2026', item: 'Talha manual 1T', category: 'Içamento', quantity: 4, unit: 'UN', status: 'Pendente', needDate: '2026-06-25', separationDate: '', sendDate: '', responsible: 'Suprimentos', notes: 'Confirmar disponibilidade.' },
    { id: 'tl-3', shutdownId: 'sd-sepetiba-2026', item: 'EPI Kit completo', category: 'EPI', quantity: 12, unit: 'KIT', status: 'Enviado', needDate: '2026-06-10', separationDate: '2026-06-06', sendDate: '2026-06-08', responsible: 'Almoxarifado', notes: '' },
  ],
  progress: [
    { id: 'pr-1', shutdownId: 'sd-saquarema-2026', stage: 'Survey', status: 'Concluído', percent: 100, plannedDate: '2026-06-05', actualDate: '2026-06-04', responsible: 'Equipe Técnica', notes: '' },
    { id: 'pr-2', shutdownId: 'sd-saquarema-2026', stage: 'Lista Ferramental', status: 'Em andamento', percent: 75, plannedDate: '2026-06-20', actualDate: '', responsible: 'Suprimentos', notes: 'Itens críticos pendentes.' },
    { id: 'pr-3', shutdownId: 'sd-saquarema-2026', stage: 'Nomeação Equipe', status: 'Em andamento', percent: 45, plannedDate: '2026-06-18', actualDate: '', responsible: 'RH / Operações', notes: '' },
    { id: 'pr-4', shutdownId: 'sd-sepetiba-2026', stage: 'Embarque Equipe', status: 'Aguardando terceiro', percent: 25, plannedDate: '2026-06-14', actualDate: '', responsible: 'Logística', notes: 'Aguardando confirmação de voo.' },
  ],
  users: [
    { id: 'usr-1', name: 'Douglas Francisco', email: 'douglasnoticias@gmail.com', role: 'Administrador', sector: 'Gestão', active: true },
    { id: 'usr-2', name: 'Planejamento STEP', email: 'planejamento@step.local', role: 'Planejamento', sector: 'Planejamento', active: true },
    { id: 'usr-3', name: 'Suprimentos STEP', email: 'suprimentos@step.local', role: 'Suprimentos', sector: 'Suprimentos', active: true },
  ],
  auditLogs: [],
};
